### ISSUE TITLE
memory increase

### ISSUE THREAD

**Issue by zhb005** [NumyAddon/NoAutoClose#6]
when I open the world map,and then chose the dungron and click,In the dungron, look up the equipment，I found the memery increased quickly, Sometimes checking backpack equipment will also cause the memory to increase.

**Comment by Numynum** [comment]
this should be resolved in the next version
the addon itself wasn't spiking in memory as such, it turned out that some important values were "tainted", which results in blizzard blaming memory usage of parts of their map, parts of their adventure journal, etc, to NoAutoClose 🙂
