### ISSUE TITLE
[BUG] NewGameUpdate broke ESC to close most windows while in combat.

### ISSUE THREAD

**Issue by p0pcake** [NumyAddon/NoAutoClose#7]
Although you can still close the spell book with ESC during a battle, you cannot close most other windows. 
These include (among others):
-World Map;
-Achievements;
-Bag;
-Talents;
-Character Panel;
-Settings…

You can't also open the Game Menu. 

It seems like the ESC button was broken altogether, but only while in a battle.

I noticed the bug about 2 days ago, and I believe the recent game update caused it.

**Comment by Numynum** [comment]
thanks for reporting it, should be fixed with next update 🙂
