### ISSUE TITLE
Stop having the quest log position reset

### ISSUE THREAD

**Issue by zalidthebur** [NumyAddon/NoAutoClose#9]
I use BlizzMove to move panels about.
With NoAutoClose enabled the quest log position keeps getting reset to it's default position when the map is opened.
The DeModal addon had the same issue and as BlizzMove author suggested NoAutoClose I thought I'd try this instead.
Can you look into this not happening.
Thanks.

**Comment by Numynum** [comment]
I'm not sure what you mean tbh
the questlog is part of the map, so their position is always tied to eachother
what is it that you're doing, and during which steps does the frame move when you wouldn't expect it to?

**Comment by zalidthebur** [comment]
If I do not have NoAutoClose enabled and move the quest log with BlizzMove it will stay in the new position when the main map is opened.
With NoAutoClose enabled it acts as normal in that I can move the questlog via BlizzMove. But opening the main map causes the quest log to revert back to its normal position.

**Comment by Numynum** [comment]
should be fixed in next release

**Comment by zalidthebur** [comment]
Thank you so much for fixing this :-)
